---

- name: Install base needed apt-packages
  apt:
    pkg:
      - python3-dev
      - python3-virtualenv
      - python3-pip
      - tcl-dev
      - tk-dev
      - python3-tk
      - git
      - virtualenv
    state: latest

- name: Install wkhtmltopdf dependencies
  apt:
    name: "{{ wkhtmltopdf_dependencies }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
